* generail
* format
#+BEGIN_SRC elisp
(ada-mode ;; package name
 . ;; annotation that this is pair data structure
 [ ;; vector of meta data
  (5 0 1) ;;curent version
  ((wisi (1 0))) ;; dependency
  "major-mode for editing Ada sources" ;; description
  tar ;; format tar or el
  ( ;;extra meta data
   (:keywords quote nil) ;; keywords
   (:url . "http://stephe-leake.org/emacs/ada-mode/emacs-ada-mode.html") ;; url
   )
  ])
#+END_SRC
* plan [5/9]
- [X] read and eval the archive-contents in ~/.emacs.d/elpa (check variable package-archive-contents)
- [X]  installed package (it's defined in package-alist)
#+BEGIN_SRC elisp
(zenburn-theme . [(2 1) nil "A low contrast color theme for Emacs."])
#+END_SRC
- [X] package the files and put it in an output dir (just use tar), how to detect the directory? ::
See function package-load-all-descriptors , check the variable package-directory-list.
- [X] generate html/javascript file for search, that's easy
- [X] just use tar command in emacs, looks tar-mode in emacs is very basic, so we use system tar instead, please note you need exclude elc file
- [ ] write the archive-contents
#+BEGIN_SRC elisp
(defun wg-write-sexp-to-file (sexp file)
  "Write the printable representation of SEXP to FILE."
  (with-temp-buffer
    (let ((print-level nil)  (print-length nil))
      (insert (format "%S" sexp)))
    (write-file file)))
#+END_SRC

- [ ] how package get the archive-contents, for local path, it only support abosolute path
could be local file content, read package--with-work-buffer. all it matters is http
- [ ] what's the queue system? use email, some email template.
- [ ] a Queue system based on email, see [[http://stackoverflow.com/questions/18361233/gmail-sending-limits]] for details, let the developer handle it by himself.

