* elpa-mirror (version 1.2.0)
Create Emacs package repository locally.

Only *already installed* packages will be included in the repository.


Please note console command *tar* and *cp* is required.

* Why
- 15 seconds to install 115 packages
- The repository could be hosted on USB/Dropbox/Github
- Tested with Emacs 23.4, Emacs 24.3, Emacs 24.4, Emacs 24.5

* Install
- Download elpa-mirror.el and place it somewhere (say "~/.emacs.d/site-lisp/elpa-mirror")
- Add below code into your .emacs,
#+BEGIN_SRC elisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/elpa-mirror")
(require 'elpa-mirror)
#+END_SRC
* Usage
Run `M-x elpamr-create-mirror-for-installed` to create local repository.

To use the local repository (say it's "~/myelpa"), insert below code into your ~/.emacs,
#+BEGIN_SRC sh
# Now elpa/marmalade/melpa site will be overrided
(setq package-archives '(("myelpa" . "~/myelpa")))
#+END_SRC

* Tips
** Change a output directory,
#+BEGIN_SRC elisp
(setq elpamr-default-output-directory "~/myelpa")
#+END_SRC
** Repository on Dropbox
Insert below code into .emacs:
#+BEGIN_SRC sh
# all-to-list will not override default elpa, so now you have to repositories, one is elpa, another is myelpa
(add-to-list 'package-archives '("myelpa" . "https://dl.dropboxusercontent.com/u/858862/myelpa/"))
#+END_SRC

My home page is at [[https://dl.dropboxusercontent.com/u/858862/myelpa/index.html]].

** Tweak the content of index.html

#+BEGIN_SRC elisp
;; default output directory
(setq elpamr-default-output-directory "~/myelpa")

;; displayed in sample code of index.html
(setq elpamr-repository-name "myelpa")

;; displayed in sample code of index.html
(setq elpamr-repository-path "http://myelpa.mydomain.com")

;; contact email, displayed in index.html
(setq elpamr-email "myname@gmail.com")

;; when exporting installed packages, ignore packages from these repositories
;; "gnu" means packages hosted on http://elpa.gnu.org
;; "melpa" means packages hosted on http://melpa.milkbox.net
(setq elpamr-exclude-package-from-repositories '("myelpa" "gnu" "melpa"))
#+END_SRC

* Report bug
- Insert below code into ~/.emacs,
#+begin_src elisp
(setq elpamr-debug t)
#+end_src
- Reproduce the bug
- Go [[https://github.com/redguardtoo/elpa-mirror]]