* elpa-mirror (version 1.2.0)

[[http://melpa.org/#/elpa-mirror][file:http://melpa.org/packages/elpa-mirror-badge.svg]] [[http://stable.melpa.org/#/elpa-mirror][file:http://stable.melpa.org/packages/elpa-mirror-badge.svg]]

Create Emacs package repository locally.

Only *locally installed* packages will be included in the repository.

Please note console command *tar* and *cp* is required.
* Why
- 15 seconds to install 115 packages
- The repository could be hosted on USB/Dropbox/Github
- Tested with Emacs 23.4, Emacs 24.3, Emacs 24.4, Emacs 24.5 on (OSX/Cygwin/Windows/Linux)
* Install
- Download elpa-mirror.el to somewhere (say "~/.emacs.d/site-lisp/elpa-mirror")
- Add below code into your ~/.emacs,
#+BEGIN_SRC elisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/elpa-mirror")
(require 'elpa-mirror)
#+END_SRC
* Usage
Run `M-x elpamr-create-mirror-for-installed` to create local repository.

To use the local repository (say it's "~/myelpa"), insert below code into your ~/.emacs,
#+BEGIN_SRC sh
# Now elpa/marmalade/melpa site will be overrided
(setq package-archives '(("myelpa" . "~/myelpa")))
#+END_SRC

* Tips
** Change a output directory,
#+BEGIN_SRC elisp
(setq elpamr-default-output-directory "~/myelpa")
#+END_SRC
** Repository on Dropbox
Insert below code into .emacs:
#+BEGIN_SRC elisp
;; all-to-list will not override default elpa.
;; So now you have two repositories.
;; One is GNU elpa. Another is myelpa
(add-to-list 'package-archives
             '("myelpa" . "https://dl.dropboxusercontent.com/u/858862/myelpa/"))
#+END_SRC
** Repository on Github
My repository is [[https://github.com/redguardtoo/myelpa]].

Insert below code into .emacs:
#+BEGIN_SRC elisp
(add-to-list 'package-archives
             '("myelpa" . "https://raw.githubusercontent.com/redguardtoo/myelpa/master/"))
#+END_SRC
** Tweak the content of index.html (OPTIONAL)
#+BEGIN_SRC elisp
;; default output directory
(setq elpamr-default-output-directory "~/myelpa")

;; displayed in sample code of index.html
(setq elpamr-repository-name "myelpa")

;; displayed in sample code of index.html
(setq elpamr-repository-path "http://myelpa.mydomain.com")

;; contact email, displayed in index.html
(setq elpamr-email "myname@gmail.com")

;; when exporting installed packages, ignore packages from these repositories
;; "gnu" means packages hosted on http://elpa.gnu.org
;; "melpa" means packages hosted on http://melpa.milkbox.net
(setq elpamr-exclude-package-from-repositories '("myelpa" "gnu" "melpa"))
#+END_SRC

* Report bug
- Insert `(setq elpamr-debug t)` into ~/.emacs
- Reproduce bug and go [[https://github.com/redguardtoo/elpa-mirror]]