* elpa-mirror (v2.1.0)

[[http://melpa.org/#/elpa-mirror][file:http://melpa.org/packages/elpa-mirror-badge.svg]] [[http://stable.melpa.org/#/elpa-mirror][file:http://stable.melpa.org/packages/elpa-mirror-badge.svg]]

Create local Emacs package repository.

Only *installed* packages will be included in the repository.

Please note console command *tar* and *cp* is required.
* Why
- 15 seconds to install 115 packages
- The repository could be hosted on USB/Dropbox/GitHub, so you can install packages behind corp firewall
- Tested with Emacs 23.4, Emacs 24.3, Emacs 24.4, Emacs 24.5 on OSX/Cygwin/Windows/Linux
* Install
- Download elpa-mirror.el to somewhere (say "~/.emacs.d/site-lisp/elpa-mirror")
- Add below code into your ~/.emacs,
#+BEGIN_SRC elisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/elpa-mirror")
(require 'elpa-mirror)
#+END_SRC

If you use native Windows Emacs, you need install Cygwin or MSYS2.
* Usage
=M-x elpamr-create-mirror-for-installed= to create local repository.

To use the repository. Say it's "~/myelpa", insert below code into your ~/.emacs,
#+BEGIN_SRC sh
# myelpa is the ONLY repository now
(setq package-archives '(("myelpa" . "~/myelpa")))
#+END_SRC
* Tips
** Change output directory,
#+BEGIN_SRC elisp
(setq elpamr-default-output-directory "~/myelpa")
#+END_SRC
** Create repository in Shell
You don't need even install elpa-mirror if running it in shell,
#+begin_src bash
mkdir -p ~/myelpa && emacs --batch -l ~/.emacs.d/init.el -l ~/any-directory-you-prefer/elpa-mirror.el --eval='(setq elpamr-default-output-directory "~/myelpa")' --eval='(elpamr-create-mirror-for-installed)'
#+end_src
** Repository on Dropbox
Insert below code into .emacs:
#+BEGIN_SRC elisp
;; all-to-list will not override default elpa.
;; So now you have two repositories.
;; One is GNU elpa. Another is myelpa
(add-to-list 'package-archives
             '("myelpa" . "https://dl.dropboxusercontent.com/u/858862/myelpa/"))
#+END_SRC
** Repository on GitHub
My repository is [[https://github.com/redguardtoo/myelpa]].

Insert below code into .emacs:
#+BEGIN_SRC elisp
(add-to-list 'package-archives
             '("myelpa" . "https://raw.githubusercontent.com/redguardtoo/myelpa/master/"))
#+END_SRC
* Report bug
- Insert =(setq elpamr-debug t)= into ~/.emacs
- Reproduce bug and go [[https://github.com/redguardtoo/elpa-mirror]]
