* elpa-mirror (version 1.1.4)
It creates Emacs package repository at *memory stick*, plus everything for hosting an ELPA web site.

Only *locally installed* packages will be included in the repository.

A use case is to create a local respository for certain Emacs setup behind corporate firewall.

* Why use elpa-mirror
- The repository could be either memory stick, or Dropbox folder, or github project
- You have full control of all packages. No dependency hell!
- Hosting your own ELPA site has *ZERO* cost.
- HTML files are optimized. Web traffic is minimum.
- The web site supports both mobile and desktop.
- tested with Emacs 23.4, Emacs 24.3, Emacs 24.4

* Install
Download elpa-mirror.el and place it somewhere (say "~/.emacs.d/my-lisp"),  then add below code into your .emacs:
#+BEGIN_SRC elisp
(add-to-list 'load-path "~/.emacs.d/lisp/")
(require 'elpa-mirror)
#+END_SRC

* Set up
Nothing to set up.

* Usage
** Create a local repository
"M-x elpamr-create-mirror-for-installed". That's it!

All files needed to host ELPA site will be output into user specified directory.

You can specify a default output directory,
#+BEGIN_SRC elisp
(setq elpamr-default-output-directory "~/myelpa")
#+END_SRC

** Use local repository
Insert below code into your .emacs, assuming "~/myelpa" is the output directory of elpamr-create-mirror-for-installed:
#+BEGIN_SRC sh
# Now elpa/marmalade/melpa site will be overrided
(setq package-archives '(("myelpa" . "~/myelpa")))
#+END_SRC

** Build a remote repository (OPTIONAL)
Upload everything into any web server or cloud service (apache/dropbox/github, etc).

Then insert below code into .emacs:
#+BEGIN_SRC sh
# all-to-list will not override default elpa, so now you have to repositories, one is elpa, another is myelpa
(add-to-list 'package-archives '("myelpa" . "https://dl.dropboxusercontent.com/u/858862/myelpa/"))
#+END_SRC

My home page is at [[https://dl.dropboxusercontent.com/u/858862/myelpa/index.html]].

* Tips (OPTIONAL)
You can tweak the content of index.html a little bit.

#+BEGIN_SRC elisp
;; default output directory
(setq elpamr-default-output-directory "~/myelpa")

;; displayed in sample code of index.html
(setq elpamr-repository-name "myelpa")

;; displayed in sample code of index.html
(setq elpamr-repository-path "http://myelpa.mydomain.com")

;; contact email, displayed in index.html
(setq elpamr-email "myname@gmail.com")

;; when exporting installed packages, ignore packages from these repositories
;; "gnu" means packages hosted on http://elpa.gnu.org
;; "melpa" means packages hosted on http://melpa.milkbox.net
(setq elpamr-exclude-package-from-repositories '("myelpa" "gnu" "melpa"))
#+END_SRC

* Contact me
You can report bugs at [[https://github.com/redguardtoo/elpa-mirror]].
