* elpa-mirror

[[http://melpa.org/#/elpa-mirror][file:http://melpa.org/packages/elpa-mirror-badge.svg]] [[http://stable.melpa.org/#/elpa-mirror][file:http://stable.melpa.org/packages/elpa-mirror-badge.svg]]

Create local Emacs package repository from *installed packages* so package upgrade never breaks.

CLI program tar is required. It's bundled with Linux, macOS, and Windows 10.

Please note if you are using Window 7 or older Windows 10 (less than build 17063) , you can still get =tar= by installing [[https://www.cygwin.com/][Cygwin]] or [[https://www.msys2.org/][MSYS2]].

* Why
- Emacs Lisp compile file (*.elc) is not portable for different versions of Emacs. So =emacs.d= copied from higher version of Emacs might crash in lower version of Emacs
- Package installation is fast. 15 seconds to install 115 packages
- The repository could be hosted on USB/Dropbox/GitHub. So you can install packages behind corp firewall
- Tested with Emacs v24.4, v24.5, v25.3, v26, v27 on OSX/Cygwin/Windows/Linux
* Install
- Download =elpa-mirror.el= to somewhere (say =~/.emacs.d/site-lisp/elpa-mirror/=)
- Add below code into your ~/.emacs,
#+begin_src elisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/elpa-mirror")
(require 'elpa-mirror)
#+end_src

* Usage
=M-x elpamr-create-mirror-for-installed= to create local repository.

To use the repository =~/myelpa/=, insert below code into your =~/.emacs=,
#+begin_src elisp
;; myelpa is the ONLY repository now, dont forget trailing slash in the directory
(setq package-archives '(("myelpa" . "~/myelpa/")))
#+end_src

To update existing local repository, run =M-x elpamr-create-mirror-for-installed= again.

BTW, you can run =elpa-mirror.el= as a independent script,
#+begin_src sh
mkdir -p ~/myelpa && emacs --batch -l ~/.emacs.d/init.el -l ~/any-directory-you-prefer/elpa-mirror.el --eval='(setq elpamr-default-output-directory "~/myelpa")' --eval='(elpamr-create-mirror-for-installed)'
#+end_src
* Tips
** Change output directory,
#+begin_src elisp
(setq elpamr-default-output-directory "~/myelpa")
#+end_src
** Repository on Dropbox
Insert below code into =~/.emacs=:
#+begin_src elisp
;; all-to-list will not override default elpa.
;; So now you have two repositories.
;; One is GNU elpa. Another is myelpa
(add-to-list 'package-archives
             '("myelpa" . "https://dl.dropboxusercontent.com/u/858862/myelpa/"))
#+end_src
** Repository on GitHub
My repository is [[https://github.com/redguardtoo/myelpa]].

Insert below code into =.emacs=:
#+begin_src elisp
(add-to-list 'package-archives
             '("myelpa" . "https://raw.githubusercontent.com/redguardtoo/myelpa/master/"))
#+end_src
* Report bug
- Insert =(setq elpamr-debug t)= into =.emacs=
- Reproduce bug and report at [[https://github.com/redguardtoo/elpa-mirror]]
